### ISSUE TITLE
Alternative Retribution Covenant Profiles

### ISSUE THREAD

**Issue by keyboardmash** [Bloodmallet/bloodytools#36]
paladin="T27_Paladin_Retribution_Venthyr"
source=default
spec=retribution
level=60
race=dark_iron_dwarf
role=attack
position=back
talents=2200302
covenant=venthyr
soulbind=theotar,soothing_shade/party_favors/templars_vindication:9:1/virtuous_command:9:1/expurgation:9:1
renown=80

head=valorous_visage_of_krexus,id=186350,bonus_id=7187/1498,gem_id=187312
neck=interplanar_keystone,id=186379,bonus_id=7187/1498/6935,gem_id=173127
shoulders=spires_of_broken_hope,id=186349,bonus_id=7187/1498,gem_id=187315
back=selfreplicating_tissue,id=186374,bonus_id=7187/1498
chest=ancient_colossus_chassis,id=186347,bonus_id=7187/1498,gem_id=187318,enchant=eternal_skirmish
wrists=vyrazs_parade_cuffs,id=186351,bonus_id=7187/1498,gem_id=187320
hands=kyras_unending_protectors,id=186346,bonus_id=7187/1498,gem_id=187319,enchant=eternal_strength
waist=shadowghast_waistguard,id=171418,bonus_id=6648/6647/6758/7054/1559/6935,gem_id=173127
legs=fateforged_legplates,id=186348,bonus_id=7187/1498
feet=greaves_of_haunting_ruination,id=186353,bonus_id=7187/1498
finger1=tarnished_insignia_of_quelthalas,id=186377,bonus_id=7187/1498/6935,gem_id=173127,enchant=tenet_of_critical_strike
finger2=arachnid_cipher_ring,id=178933,bonus_id=6536/1566/6646/6935,gem_id=173127,enchant=tenet_of_critical_strike
trinket1=inscrutable_quantum_device,id=179350,bonus_id=6536/1566/6646
trinket2=old_warriors_soul,id=186438,bonus_id=7187/1498
main_hand=jaithys_the_prison_blade,id=186410,bonus_id=7187/7748/1498,enchant=sinful_revelation

paladin="T27_Paladin_Retribution_Necrolord"
source=default
spec=retribution
level=60
race=dark_iron_dwarf
role=attack
position=back
talents=2200303
covenant=necrolord
soulbind=marileth,volatile_solvent/kevins_oozeling/templars_vindication:9:1/virtuous_command:9:1/expurgation:9:1
renown=80

head=valorous_visage_of_krexus,id=186350,bonus_id=7187/1498,gem_id=187312
neck=interplanar_keystone,id=186379,bonus_id=7187/1498/6935,gem_id=173127
shoulders=spires_of_broken_hope,id=186349,bonus_id=7187/1498,gem_id=187315
back=grimveiled_cape,id=173242,bonus_id=6648/6647/6758/7064/1559
chest=ancient_colossus_chassis,id=186347,bonus_id=7187/1498,gem_id=187318,enchant=eternal_skirmish
wrists=vyrazs_parade_cuffs,id=186351,bonus_id=7187/1498,gem_id=187320
hands=kyras_unending_protectors,id=186346,bonus_id=7187/1498,gem_id=187319,enchant=eternal_strength
waist=binding_of_dark_destinies,id=186352,bonus_id=7187/1498/6935,gem_id=173127
legs=fateforged_legplates,id=186348,bonus_id=7187/1498
feet=greaves_of_haunting_ruination,id=186353,bonus_id=7187/1498
finger1=tarnished_insignia_of_quelthalas,id=186377,bonus_id=7187/1498/6935,gem_id=173127,enchant=tenet_of_critical_strike
finger2=arachnid_cipher_ring,id=178933,bonus_id=6536/1566/6646/6935,gem_id=173127,enchant=tenet_of_critical_strike
trinket1=inscrutable_quantum_device,id=179350,bonus_id=6536/1566/6646
trinket2=old_warriors_soul,id=186438,bonus_id=7187/1498
main_hand=jaithys_the_prison_blade,id=186410,bonus_id=7187/7748/1498,enchant=sinful_revelation

paladin="T27_Paladin_Retribution_Night_Fae"
source=default
spec=retribution
level=60
race=dark_iron_dwarf
role=attack
position=back
talents=2200302
covenant=night_fae
soulbind=dreamweaver,field_of_blossoms/dream_delver/templars_vindication:9:1/virtuous_command:9:1/expurgation:9:1
renown=80

head=valorous_visage_of_krexus,id=186350,bonus_id=7187/1498,gem_id=187312
neck=interplanar_keystone,id=186379,bonus_id=7187/1498/6935,gem_id=173127
shoulders=spires_of_broken_hope,id=186349,bonus_id=7187/1498,gem_id=187315
back=grimveiled_cape,id=173242,bonus_id=6648/6647/6758/7064/1559
chest=ancient_colossus_chassis,id=186347,bonus_id=7187/1498,gem_id=187318,enchant=eternal_skirmish
wrists=vyrazs_parade_cuffs,id=186351,bonus_id=7187/1498,gem_id=187320
hands=kyras_unending_protectors,id=186346,bonus_id=7187/1498,gem_id=187319,enchant=eternal_strength
waist=binding_of_dark_destinies,id=186352,bonus_id=7187/1498/6935,gem_id=173127
legs=fateforged_legplates,id=186348,bonus_id=7187/1498
feet=greaves_of_haunting_ruination,id=186353,bonus_id=7187/1498
finger1=tarnished_insignia_of_quelthalas,id=186377,bonus_id=7187/1498/6935,gem_id=173127,enchant=tenet_of_critical_strike
finger2=arachnid_cipher_ring,id=178933,bonus_id=6536/1566/6646/6935,gem_id=173127,enchant=tenet_of_critical_strike
trinket1=inscrutable_quantum_device,id=179350,bonus_id=6536/1566/6646
trinket2=old_warriors_soul,id=186438,bonus_id=7187/1498
main_hand=jaithys_the_prison_blade,id=186410,bonus_id=7187/7748/1498,enchant=sinful_revelation

**Comment by Bloodmallet** [comment]
Thank you for the profiles. Are these for HecticAddCleave too?

**Comment by Bloodmallet** [comment]
profiles are added. friday resimulation should pick them up.
