### ISSUE TITLE
Error during Armory sim with shadowpriest

### ISSUE THREAD

**Issue by choseh** [Bloodmallet/bloodytools#7]
018-09-15 19:12:37,566 - ERROR - ERROR: An Error occured during simulation.
2018-09-15 19:12:37,566 - ERROR - args: ['../../simulationcraft/engine/simc', '28d218f5-67bf-49b0-b3a5-55c01db1cce7.simc']
2018-09-15 19:12:37,566 - ERROR - stdout: SimulationCraft 801-02 for World of Warcraft 8.0.1 Live (wow build 27602, git build bfa-dev 6db2df0)

@
Simulating... ( iterations=20000, threads=6, target_error=1.000,  max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )

@Generating Baseline: 1/1 [===================>] 103/103 Mean=10713 Error=0.475% 54msec
Profilesets (3*2): 1/1 [===================>] avg=0s done=476.713ms left=0s
@Profilesets (3*2): 1/2 [=========>..........] avg=0s done=1s left=0s
@@Profilesets (3*2): 2/3 [============>.......] avg=17.294ms done=2s left=0s
@Profilesets (3*2): 3/4 [==============>.....] avg=22.808ms done=2s left=0s
@Profilesets (3*2): 4/5 [===============>....] avg=25.677ms done=3s left=0s
@Profilesets (3*2): 5/6 [================>...] avg=28.131ms done=3s left=0s
@Profilesets (3*2): 6/7 [================>...] avg=29.254ms done=4s left=0s
@Profilesets (3*2): 7/8 [=================>..] avg=29.93ms done=4s left=0s
@Profilesets (3*2): 8/9 [=================>..] avg=30.566ms done=5s left=0s
@Profilesets (3*2): 9/10 [=================>..] avg=31.173ms done=6s left=0s
@Profilesets (3*2): 10/11 [=================>..] avg=31.671ms done=7s left=0s
@Profilesets (3*2): 11/12 [=================>..] avg=32.206ms done=7s left=0s
@Profilesets (3*2): 12/13 [=================>..] avg=32.363ms done=8s left=0s
@Profilesets (3*2): 13/14 [==================>.] avg=32.484ms done=8s left=0s
@Profilesets (3*2): 14/15 [==================>.] avg=32.687ms done=9s left=0s
@Profilesets (3*2): 15/16 [==================>.] avg=33.033ms done=10s left=0s
@Profilesets (3*2): 16/17 [==================>.] avg=33.32ms done=10s left=0s
@Profilesets (3*2): 17/18 [==================>.] avg=33.385ms done=11s left=0s
@Profilesets (3*2): 18/19 [==================>.] avg=33.409ms done=11s left=0s
@Profilesets (3*2): 19/20 [==================>.] avg=33.473ms done=12s left=0s
@Profilesets (3*2): 20/21 [==================>.] avg=33.515ms done=13s left=0s
@Profilesets (3*2): 21/22 [==================>.] avg=33.548ms done=13s left=0s
@Profilesets (3*2): 22/23 [==================>.] avg=33.673ms done=14s left=0s
@Profilesets (3*2): 23/24 [==================>.] avg=33.665ms done=14s left=0s
@Profilesets (3*2): 24/25 [==================>.] avg=33.692ms done=15s left=0s
@Profilesets (3*2): 25/26 [==================>.] avg=33.748ms done=15s left=0s
@Profilesets (3*2): 26/27 [==================>.] avg=33.787ms done=16s left=0s
@Profilesets (3*2): 27/28 [==================>.] avg=33.796ms done=16s left=0s
@Profilesets (3*2): 28/29 [==================>.] avg=33.888ms done=17s left=0s
@Profilesets (3*2): 29/30 [==================>.] avg=33.915ms done=18s left=0s
@Profilesets (3*2): 30/31 [==================>.] avg=34.018ms done=18s left=0s
@Profilesets (3*2): 31/32 [==================>.] avg=34.074ms done=19s left=0s
@Profilesets (3*2): 32/33 [==================>.] avg=34.095ms done=19s left=0s
@Profilesets (3*2): 33/34 [==================>.] avg=34.114ms done=20s left=0s
@Profilesets (3*2): 34/35 [==================>.] avg=34.119ms done=20s left=0s
@Profilesets (3*2): 35/36 [==================>.] avg=34.159ms done=21s left=0s
@Profilesets (3*2): 36/37 [==================>.] avg=34.136ms done=21s left=0s
@Profilesets (3*2): 37/38 [==================>.] avg=34.381ms done=22s left=0s
@Profilesets (3*2): 38/39 [==================>.] avg=34.381ms done=22s left=0s
@Profilesets (3*2): 39/40 [===================>] avg=34.381ms done=23s left=0s
@Profilesets (3*2): 40/41 [===================>] avg=34.456ms done=23s left=0s
@Profilesets (3*2): 41/42 [===================>] avg=34.564ms done=24s left=0s
@Profilesets (3*2): 42/43 [===================>] avg=34.614ms done=24s left=0s
@Profilesets (3*2): 43/44 [===================>] avg=34.584ms done=25s left=0s
@Profilesets (3*2): 44/45 [===================>] avg=34.722ms done=26s left=0s
@Profilesets (3*2): 45/46 [===================>] avg=34.704ms done=26s left=0s
@Profilesets (3*2): 46/47 [===================>] avg=34.687ms done=27s left=0s
@Profilesets (3*2): 47/48 [===================>] avg=34.679ms done=27s left=0s
@Profilesets (3*2): 48/49 [===================>] avg=35.427ms done=28s left=0s
@Profilesets (3*2): 49/50 [===================>] avg=35.401ms done=28s left=0s
@Profilesets (3*2): 50/51 [===================>] avg=35.417ms done=29s left=0s
@Profilesets (3*2): 51/52 [===================>] avg=35.417ms done=30s left=0s
@Profilesets (3*2): 52/53 [===================>] avg=35.406ms done=30s left=0s
@Profilesets (3*2): 53/54 [===================>] avg=35.524ms done=31s left=0s
@Profilesets (3*2): 54/55 [===================>] avg=35.581ms done=31s left=0s
@Profilesets (3*2): 55/56 [===================>] avg=35.556ms done=32s left=0s
@Profilesets (3*2): 56/57 [===================>] avg=35.576ms done=32s left=0s
@Profilesets (3*2): 57/58 [===================>] avg=35.589ms done=33s left=0s
@Profilesets (3*2): 58/59 [===================>] avg=35.6ms done=33s left=0s
@Profilesets (3*2): 59/60 [===================>] avg=35.594ms done=34s left=0s
@Profilesets (3*2): 60/61 [===================>] avg=35.593ms done=35s left=0s
@Profilesets (3*2): 61/62 [===================>] avg=35.586ms done=35s left=0s
@Profilesets (3*2): 62/63 [===================>] avg=35.644ms done=36s left=0s
@Profilesets (3*2): 63/64 [===================>] avg=35.626ms done=36s left=0s
@Profilesets (3*2): 64/65 [===================>] avg=35.614ms done=37s left=0s
@Profilesets (3*2): 65/66 [===================>] avg=35.579ms done=37s left=0s
@Profilesets (3*2): 66/67 [===================>] avg=35.581ms done=38s left=0s
@Profilesets (3*2): 67/68 [===================>] avg=35.576ms done=38s left=0s
@Profilesets (3*2): 68/69 [===================>] avg=35.598ms done=39s left=0s
@Profilesets (3*2): 69/70 [===================>] avg=35.609ms done=39s left=0s
@Profilesets (3*2): 70/71 [===================>] avg=35.597ms done=40s left=0s
@Profilesets (3*2): 71/72 [===================>] avg=35.576ms done=41s left=0s
@Profilesets (3*2): 72/73 [===================>] avg=35.556ms done=41s left=0s
@Profilesets (3*2): 73/74 [===================>] avg=35.539ms done=42s left=0s
@Profilesets (3*2): 74/75 [===================>] avg=35.524ms done=42s left=0s
@Profilesets (3*2): 75/76 [===================>] avg=35.52ms done=43s left=0s
@Profilesets (3*2): 76/77 [===================>] avg=35.513ms done=43s left=0s
@Profilesets (3*2): 77/78 [===================>] avg=35.491ms done=44s left=0s
@Profilesets (3*2): 78/79 [===================>] avg=35.484ms done=45s left=0s
@Profilesets (3*2): 79/80 [===================>] avg=35.504ms done=45s left=0s
simc: buff/sc_buff.cpp:1496: virtual void buff_t::start(int, double, timespan_adl_barrier::timespan_t): Assertion `!tick_event' failed.

2018-09-15 19:12:37,566 - ERROR - name=value error? Check your input! Maybe your links to already existing profiles are wrong. They need to be relative links from bloodytools to your SimulationCraft directory.
2018-09-15 19:12:37,566 - ERROR - Patchwerk azerite_trait simulation for Priest Shadow failed. SimulationCraft 801-02 for World of Warcraft 8.0.1 Live (wow build 27602, git build bfa-dev 6db2df0)

@
Simulating... ( iterations=20000, threads=6, target_error=1.000,  max_time=300, vary_combat_length=0.20, optimal_raid=1, fight_style=Patchwerk )

@Generating Baseline: 1/1 [===================>] 103/103 Mean=10713 Error=0.475% 54msec
Profilesets (3*2): 1/1 [===================>] avg=0s done=476.713ms left=0s
@Profilesets (3*2): 1/2 [=========>..........] avg=0s done=1s left=0s
@@Profilesets (3*2): 2/3 [============>.......] avg=17.294ms done=2s left=0s
@Profilesets (3*2): 3/4 [==============>.....] avg=22.808ms done=2s left=0s
@Profilesets (3*2): 4/5 [===============>....] avg=25.677ms done=3s left=0s
@Profilesets (3*2): 5/6 [================>...] avg=28.131ms done=3s left=0s
@Profilesets (3*2): 6/7 [================>...] avg=29.254ms done=4s left=0s
@Profilesets (3*2): 7/8 [=================>..] avg=29.93ms done=4s left=0s
@Profilesets (3*2): 8/9 [=================>..] avg=30.566ms done=5s left=0s
@Profilesets (3*2): 9/10 [=================>..] avg=31.173ms done=6s left=0s
@Profilesets (3*2): 10/11 [=================>..] avg=31.671ms done=7s left=0s
@Profilesets (3*2): 11/12 [=================>..] avg=32.206ms done=7s left=0s
@Profilesets (3*2): 12/13 [=================>..] avg=32.363ms done=8s left=0s
@Profilesets (3*2): 13/14 [==================>.] avg=32.484ms done=8s left=0s
@Profilesets (3*2): 14/15 [==================>.] avg=32.687ms done=9s left=0s
@Profilesets (3*2): 15/16 [==================>.] avg=33.033ms done=10s left=0s
@Profilesets (3*2): 16/17 [==================>.] avg=33.32ms done=10s left=0s
@Profilesets (3*2): 17/18 [==================>.] avg=33.385ms done=11s left=0s
@Profilesets (3*2): 18/19 [==================>.] avg=33.409ms done=11s left=0s
@Profilesets (3*2): 19/20 [==================>.] avg=33.473ms done=12s left=0s
@Profilesets (3*2): 20/21 [==================>.] avg=33.515ms done=13s left=0s
@Profilesets (3*2): 21/22 [==================>.] avg=33.548ms done=13s left=0s
@Profilesets (3*2): 22/23 [==================>.] avg=33.673ms done=14s left=0s
@Profilesets (3*2): 23/24 [==================>.] avg=33.665ms done=14s left=0s
@Profilesets (3*2): 24/25 [==================>.] avg=33.692ms done=15s left=0s
@Profilesets (3*2): 25/26 [==================>.] avg=33.748ms done=15s left=0s
@Profilesets (3*2): 26/27 [==================>.] avg=33.787ms done=16s left=0s
@Profilesets (3*2): 27/28 [==================>.] avg=33.796ms done=16s left=0s
@Profilesets (3*2): 28/29 [==================>.] avg=33.888ms done=17s left=0s
@Profilesets (3*2): 29/30 [==================>.] avg=33.915ms done=18s left=0s
@Profilesets (3*2): 30/31 [==================>.] avg=34.018ms done=18s left=0s
@Profilesets (3*2): 31/32 [==================>.] avg=34.074ms done=19s left=0s
@Profilesets (3*2): 32/33 [==================>.] avg=34.095ms done=19s left=0s
@Profilesets (3*2): 33/34 [==================>.] avg=34.114ms done=20s left=0s
@Profilesets (3*2): 34/35 [==================>.] avg=34.119ms done=20s left=0s
@Profilesets (3*2): 35/36 [==================>.] avg=34.159ms done=21s left=0s
@Profilesets (3*2): 36/37 [==================>.] avg=34.136ms done=21s left=0s
@Profilesets (3*2): 37/38 [==================>.] avg=34.381ms done=22s left=0s
@Profilesets (3*2): 38/39 [==================>.] avg=34.381ms done=22s left=0s
@Profilesets (3*2): 39/40 [===================>] avg=34.381ms done=23s left=0s
@Profilesets (3*2): 40/41 [===================>] avg=34.456ms done=23s left=0s
@Profilesets (3*2): 41/42 [===================>] avg=34.564ms done=24s left=0s
@Profilesets (3*2): 42/43 [===================>] avg=34.614ms done=24s left=0s
@Profilesets (3*2): 43/44 [===================>] avg=34.584ms done=25s left=0s
@Profilesets (3*2): 44/45 [===================>] avg=34.722ms done=26s left=0s
@Profilesets (3*2): 45/46 [===================>] avg=34.704ms done=26s left=0s
@Profilesets (3*2): 46/47 [===================>] avg=34.687ms done=27s left=0s
@Profilesets (3*2): 47/48 [===================>] avg=34.679ms done=27s left=0s
@Profilesets (3*2): 48/49 [===================>] avg=35.427ms done=28s left=0s
@Profilesets (3*2): 49/50 [===================>] avg=35.401ms done=28s left=0s
@Profilesets (3*2): 50/51 [===================>] avg=35.417ms done=29s left=0s
@Profilesets (3*2): 51/52 [===================>] avg=35.417ms done=30s left=0s
@Profilesets (3*2): 52/53 [===================>] avg=35.406ms done=30s left=0s
@Profilesets (3*2): 53/54 [===================>] avg=35.524ms done=31s left=0s
@Profilesets (3*2): 54/55 [===================>] avg=35.581ms done=31s left=0s
@Profilesets (3*2): 55/56 [===================>] avg=35.556ms done=32s left=0s
@Profilesets (3*2): 56/57 [===================>] avg=35.576ms done=32s left=0s
@Profilesets (3*2): 57/58 [===================>] avg=35.589ms done=33s left=0s
@Profilesets (3*2): 58/59 [===================>] avg=35.6ms done=33s left=0s
@Profilesets (3*2): 59/60 [===================>] avg=35.594ms done=34s left=0s
@Profilesets (3*2): 60/61 [===================>] avg=35.593ms done=35s left=0s
@Profilesets (3*2): 61/62 [===================>] avg=35.586ms done=35s left=0s
@Profilesets (3*2): 62/63 [===================>] avg=35.644ms done=36s left=0s
@Profilesets (3*2): 63/64 [===================>] avg=35.626ms done=36s left=0s
@Profilesets (3*2): 64/65 [===================>] avg=35.614ms done=37s left=0s
@Profilesets (3*2): 65/66 [===================>] avg=35.579ms done=37s left=0s
@Profilesets (3*2): 66/67 [===================>] avg=35.581ms done=38s left=0s
@Profilesets (3*2): 67/68 [===================>] avg=35.576ms done=38s left=0s
@Profilesets (3*2): 68/69 [===================>] avg=35.598ms done=39s left=0s
@Profilesets (3*2): 69/70 [===================>] avg=35.609ms done=39s left=0s
@Profilesets (3*2): 70/71 [===================>] avg=35.597ms done=40s left=0s
@Profilesets (3*2): 71/72 [===================>] avg=35.576ms done=41s left=0s
@Profilesets (3*2): 72/73 [===================>] avg=35.556ms done=41s left=0s
@Profilesets (3*2): 73/74 [===================>] avg=35.539ms done=42s left=0s
@Profilesets (3*2): 74/75 [===================>] avg=35.524ms done=42s left=0s
@Profilesets (3*2): 75/76 [===================>] avg=35.52ms done=43s left=0s
@Profilesets (3*2): 76/77 [===================>] avg=35.513ms done=43s left=0s
@Profilesets (3*2): 77/78 [===================>] avg=35.491ms done=44s left=0s
@Profilesets (3*2): 78/79 [===================>] avg=35.484ms done=45s left=0s
@Profilesets (3*2): 79/80 [===================>] avg=35.504ms done=45s left=0s
simc: buff/sc_buff.cpp:1496: virtual void buff_t::start(int, double, timespan_adl_barrier::timespan_t): Assertion `!tick_event' failed.

Steps to reproduce:

1. create Tier22 Priest Shadow.simc with:
armory=eu,azshara,unholypriest
apikey=yourapikey
head=,id=161555

2. run bloodytools
3. gaze at error

**Comment by Bloodmallet** [comment]
```
simc: buff/sc_buff.cpp:1496: virtual void buff_t::start(int, double, timespan_adl_barrier::timespan_t): Assertion `!tick_event' failed.
```

Does this error occur with the baseline profile and the same talent and azerite traits layout too? because that error should be from SimulationCraft and wihtin it instead of introduced by bloodytools.
